require "test_helper"

class UrlTest < ActiveSupport::TestCase
  test 'should not save url without original_url' do
    url = Url.new
    assert_not url.save, 'Saved the url without a original_url'
  end

  test 'token generated by long url must have 8 characters' do
    url = FactoryBot.create(:url)
    url.save
    assert_equal 8, url.token.size
  end

  test 'token generated by long url must be equal to encoded token' do
    url = FactoryBot.create(:url)
    token = url.token
    encoded_token_test = Base64.encode64(url.original_url)[0..7]
    assert_equal encoded_token_test, token
  end
end
